# fly.toml app configuration file generated for open-alpha-arena on 2025-11-09T22:52:59+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'open-alpha-arena'
primary_region = 'sin'

[build]

[[services]]
  internal_port = 5611
  protocol = 'tcp'
  processes = ['app']
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']
    force_https = false

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = false

  [[services.http_checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
